// This file is auto-generated by Lovable. Do not modify it.

// Removed Lovable cloud-auth-js import – using Supabase auth instead
import { supabase } from "../supabase/client";
// No longer needed

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      // Use Supabase OAuth for Google provider
      const result = await supabase.auth.signInWithOAuth({
        provider: "google",
        options: {
          redirectTo: opts?.redirect_uri,
          ...(opts?.extraParams || {}),
        },
      });
      if (result.error) {
        return { error: result.error };
      }
      // Supabase handles session automatically; no redirection needed here
      return { redirected: false };
    },
  },
};
