/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemLoginRouteImport } from './routes/system-login'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as ApiOrdersCreateRouteImport } from './routes/api/orders.create'

const SystemLoginRoute = SystemLoginRouteImport.update({
  id: '/system-login',
  path: '/system-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersCreateRoute = ApiOrdersCreateRouteImport.update({
  id: '/api/orders/create',
  path: '/api/orders/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/showroom': typeof ShowroomRoute
  '/start-project': typeof StartProjectRoute
  '/system-login': typeof SystemLoginRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/api/orders/create': typeof ApiOrdersCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/showroom': typeof ShowroomRoute
  '/start-project': typeof StartProjectRoute
  '/system-login': typeof SystemLoginRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/api/orders/create': typeof ApiOrdersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/showroom': typeof ShowroomRoute
  '/start-project': typeof StartProjectRoute
  '/system-login': typeof SystemLoginRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/api/orders/create': typeof ApiOrdersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/home'
    | '/orders'
    | '/showroom'
    | '/start-project'
    | '/system-login'
    | '/api/upload-image'
    | '/category/$slug'
    | '/product/$id'
    | '/api/orders/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/home'
    | '/orders'
    | '/showroom'
    | '/start-project'
    | '/system-login'
    | '/api/upload-image'
    | '/category/$slug'
    | '/product/$id'
    | '/api/orders/create'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/home'
    | '/orders'
    | '/showroom'
    | '/start-project'
    | '/system-login'
    | '/api/upload-image'
    | '/category/$slug'
    | '/product/$id'
    | '/api/orders/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  HomeRoute: typeof HomeRoute
  OrdersRoute: typeof OrdersRoute
  ShowroomRoute: typeof ShowroomRoute
  StartProjectRoute: typeof StartProjectRoute
  SystemLoginRoute: typeof SystemLoginRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiOrdersCreateRoute: typeof ApiOrdersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-login': {
      id: '/system-login'
      path: '/system-login'
      fullPath: '/system-login'
      preLoaderRoute: typeof SystemLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/create': {
      id: '/api/orders/create'
      path: '/api/orders/create'
      fullPath: '/api/orders/create'
      preLoaderRoute: typeof ApiOrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  HomeRoute: HomeRoute,
  OrdersRoute: OrdersRoute,
  ShowroomRoute: ShowroomRoute,
  StartProjectRoute: StartProjectRoute,
  SystemLoginRoute: SystemLoginRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
  ApiOrdersCreateRoute: ApiOrdersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
